### ISSUE TITLE
spline.c

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/reboundx#13]
## Tasks
- [x] Review Python interpolation examples (Jupyter Notebooks)
- [x] Read &sect;&sect; 3.0, 3.1, and 3.3 of _Numerical Recipes_
- [x] Write, plot, and test spline algorithm in Python ([notebook](https://github.com/sabaronett/demo-lab/blob/master/nr/03interp/nr_spline.ipynb))
- [x] Write standalone `spline.c` w/ sample datasets and Python reader/plotter ([repo](https://github.com/sabaronett/demo-lab/tree/master/nr/03interp/c))
- [x] Adapt `spline.c` as an "effect" w/ an example `problem.c` #17 
- [x] Determine where best to implement functions in REBOUNDx #17 
- [x] Read &sect;&sect; 2.0&ndash;2.4, 3.4, 3.5 of _Numerical Recipes_
- [x] When #14 is done, verify results with MESA data (against SciPy interpolate) (to be effectively tested in #17) 

## Notes
- Created from Dan's https://github.com/sabaronett/reboundx/issues/5#issuecomment-580754123.
- Is it best to write these (convenience) functions (for reading in and splining) in our effect.c or somewhere else to make it more "modular" and reusable?
- ~How best to save interpolation function to disk (e.g., `.bin` file)?~
   - ~SciPy's Cubic Spline, e.g., `PPoly` instance  ([reference](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CubicSpline.html#scipy.interpolate.CubicSpline))~
   - ~GSL's Interpolation library, e.g., Steffen spline (https://www.gnu.org/software/gsl/doc/html/interp.html)~
- ~How can `[effects].c` "read" the stored `interpolation.bin` file without including GSL or any other libraries?~
   - ~Check <cmath> ([math.h](http://www.cplusplus.com/reference/cmath/)) documentation~

## References
- Press, Teukolsky, Vetterling & Flannery, _Numerical Recipes in C: The Art of Scientific Computing_, 2nd Ed. (2002): &sect;&sect; 3.0&ndash;3.5.
- _GSL_ [source](http://git.savannah.gnu.org/cgit/gsl.git/tree/interpolation)
- _GSL_ [documentation](https://www.gnu.org/software/gsl/doc/html/interp.html#sec-interpolation)

**Comment by sabaronett** [comment]
> b) Write C code (e.g. from Numerical Recipes) that takes the MESA outputs and fits spline coefficients...

_Originally posted by @dtamayo in https://github.com/sabaronett/reboundx/issues/5#issuecomment-581561093_

I was meeting with Dr. Steffen before your last comment, and that's exactly what he had suggested. Although it'll be somewhat more difficult than (a), I think this is the way to go as it'll make things easier for the end-user. Namely, they generate some stellar data from MESA to a text file (out-of-the-box functionality), specify its path in a required parameter for REBOUNDx, and our code takes care of the rest: reading in and splining the data (just once) and holding it in memory.

I wrote some interpolation code for a scientific Python course last semester that I'll review. I'll also  looking at/compare with GSL's source for cubic/Steffen splines, keeping _Numerical Recipes_ on hand just in case 😏.

I guess one question is whether you think it's best to write these (convenience) functions (for reading in and splining) in our `effect.c` or somewhere else to make it more "modular" and reusable.

**Comment by dtamayo** [comment]
It would be awesome to write it in a spline.c file. I think many future effects could make use of it. Thanks for all the great work and energy on this!

**Comment by sabaronett** [comment]
Absolutely!

**Comment by sabaronett** [comment]
Remaining task list items to be addressed/tested in #17. 

Closing issue.
