### ISSUE TITLE
mesa_reader.c

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/reboundx#14]
See https://github.com/sabaronett/reboundx/issues/5#issuecomment-581561093 and https://github.com/sabaronett/reboundx/issues/13#issuecomment-581680618 for context.

# Goal
Initially write standalone code/functions in C to read in a MESA data file and store it in an array. Once verified working, implement in REBOUNDx.

## Tasks
- [x] Review Python source for PyMesaReader ([docs](https://billwolf.space/py_mesa_reader/index.html))
- [ ] Port code to C
- [ ] Utilize [C Standard Input and Output Library](http://www.cplusplus.com/reference/cstdio/) `<stdio.h>`
- [ ] Test with MESA data, e.g., `LOGS/history_to_wd.data`
- [ ] (Recommended) Plot imported MESA data with [gnuplot ](http://www.gnuplot.info/) for verification
- [ ] Determine where best to implement in REBOUNDx

**Comment by sabaronett** [comment]
@Nofe4108, while I work on #13, do you think you can work on this issue? If not, or if you need some help, I can get to it after I finish the C spline code. Thanks.

**Comment by Nofe4108** [comment]
Definitely. I was already starting to figure out how to read in data in C last week, so I'll just continue to work on that.

**Comment by sabaronett** [comment]
Awesome. Thanks man. Just let me know if you need any help.

By the way, you may want to look into  [gnuplot ](http://www.gnuplot.info/) when you're ready to graph the imported MESA data with your code to verify it worked/looks right.

**Comment by Nofe4108** [comment]
I looked at the source code for PyMesaReader, and I believe that two of the classes won't be necessary for what we're trying to do. The _MesaLogDir_ and _MesaProfileIndex_ seem to be there just to help people navigate the LOGS directory and access the history file by using model numbers and stuff like that, which we don't really need. I also cut out a few of the functions in the _MesaData_ class that are used to read different file types and just kept the one that reads in .data files. 

The edited source code can be found here: https://github.com/Nofe4108/reboundx/blob/MESAreader/py_mesa_reader_source.py

The C version of the Mesa reader I just started on can be found here: https://github.com/Nofe4108/reboundx/blob/MESAreader/C_mesa_reader.c

Also looking at the python code there are many functions within the classes, which I know you can't really do in C with its structures. I read that you can put a function pointer within a structure, but I'm not sure if that's the best way to handle this sort of issue. What do you recommend? 

Also the PyMesaReader uses numpy to read in the data from the txt file: https://github.com/Nofe4108/reboundx/blob/0f86bbcfab3ed5feda3b920cbfdf81155f47e952/py_mesa_reader_source.py#L71-L73

I could try and figure out a way to read in the .data using C with the same functionalities as this numpy function, but is there a C library that you know of that can do the same thing?

**Comment by sabaronett** [comment]
This is awesome! Good work so far.

Couple things and responses to your questions:
- Just like the `spline.c` code I'll be working on, @dtamayo will likely want to include `mesa_reader.c` as it's own add'l REBOUNDx "effect," although just like the spline it's really more of a functionality add-on or extension tool to be used in conjunction with other "physics" effects/forces.
- Given it's ultimate implementation, at some point you'll want to copy, paste and modify the main header comment from the existing forces that contains the license and formatting for proper documentation.
- This also segues into solving the "function within structure" issue: ultimately the `struct MesaData` will be registered and stored as an add'l, [custom type](https://reboundx.readthedocs.io/en/latest/add_effect.html#adding-custom-types) param in `core.c`. Then you can write whatever convenience functions you want or need in `mesa_reader.c` (see some of the other forces, like `tides_precession.c` and `central_force.c`, for convenience function examples).
- The overarching goal is to not have REBOUNDx require other C libraries as dependencies, so we have to make due with what's already included, e.g., _C Standard Input and Output Library_ [<stdio.h>](http://www.cplusplus.com/reference/cstdio/). If their methods are too rudimentary, you can try writing add'l convenience functions to get the job done, or see if someone online has already written what you want to achieve.

**Comment by Nofe4108** [comment]
I wasn't able to do much this week, but I took a look at the _C Standard Input and Output Library_ and I think the function fscanf is what I want to use for this, but I'll also probably have to create some additional convenience functions to match what the Python version does. I've tried searching for some file input code that people have already made that will help me with this, and I found a few candidates, but I may just have to make it all myself. 

I know this isn't the proper place, but how is the spline code going? I just want to see how things are going, so I can get a time frame for everything.

**Comment by sabaronett** [comment]
Sounds like you're on the right track. Don't hesitate to ask if you have any questions or run into an issue.

Not sure if you saw #6, but I had focused on getting our first pull request submitted for Dan to review, which was done this past Sunday, so I haven't had a chance to work on the spline code. Probably won't have time to get to it until next week at the latest. I'll keep you posted, but if I happen to finish the spline code before you finish the mesa_reader (unlikely) I can always help you out by splitting up the work left to do. No worries though, focus on your classes and things.

**Comment by Nofe4108** [comment]
Wow that's great! Keep me updated on how that goes! 

For the C mesa_reader I'm still trying to figure out the best way to port it over, what functions I need to add, and overall make a general outline for what I should do. I'm not sure if I should try and do exactly what they did for the python version or make my own more simplified version. I should have plenty of questions for you on this coming up in the near future.

**Comment by dtamayo** [comment]
If you have a python reader, is a simpler option just to read it in python,
write what you need to a text file, and read that in C, knowing exactly the
formatting you put in?

**Comment by sabaronett** [comment]
@Nofe4108, you can try Dan's suggestion as a jumping off point or if you get stuck. I was going to suggest approaching it same way you figured out the Python scripts to write out the planets' orbital elements (in our simulation.py) and later read in (in the sim_reader.py). Get basic C input/output down, storage in C arrays, and then slowly build up to more complicated input files, until you can read a MESA history file. In fact, you can strip down an existing MESA file to one/two columns to start. Along the way, you can refer to how PyMesaReader does things as you get to them, but don't let it dictate how to proceed.

Let me know if you need any help.

**Comment by Nofe4108** [comment]
I will definitely use that suggestion. I was thinking I could use PyMesaReader to make individual text files for each column of data, and just read those much simpler files into C. This will allow me to start learning how to read basic files into C like you said, and also give you the data you need for testing the spline code in the future even if I haven't finished the full CMesaReader code yet.

**Comment by Nofe4108** [comment]
Sorry for the lack of updates. The last couple of weeks have been pretty hectic, so I haven't made that much progress, but here's what I've done so far. I used MesaReader in a python program to create text files for the MESA data for each category of data from the simulation like the Sun's age and radius. In these files each number is simply placed on a new line and that's all these files contain. I then went over to C and read one of these files in to try and get the data into an array. I have the array all setup for the data but I'm having problems using _fscanf_ to get each number into this array. I've tried a couple of different methods and so far none of them have worked. I'll send over all of my code in a little while so you can take a look at it and see if you can find what's wrong with it. Also If you have any other suggestions please let me know.

**Comment by sabaronett** [comment]
No worries. What you've done sounds good, especially since the way things are headed with the spline code; we'll likely want to allow the user to submit data files containing only a list of times (stellar age) and a single quantity (like mass, luminosity, etc.), as opposed to a single file with multiple quantities. This keeps things on our end simpler and flexible for the end user.

As for the input/parsing issues, I'll take a look after I'm finished with my first draft of the spline stuff (now called `stellar_evo.c`). If you happen to take another crack at it before I do, try something simpler with `fscanf` (or similar), like a simple program where you read in a single number from a file, store it in an int/double, and then perform a simple operation on it, just to see if it worked as expected. For example, I had an assignment in a C++ course where we had to read in something like:
```
5 + 6
1 - 2
```
character by character (including the newline character `\n` at the end of each line), which would inform our program to perform the requisite operations. I'll likely review that assignment (and send it to you) when attempting to troubleshoot your issue. I think once you've got reading in and storing a number down pat, you should be able to figure out how to then store it in an array.

By the way, one thing that might make things easier is to declare a variable `int n` that represents the number of lines/data points to be read in. This wouldn't be something unreasonable to ask of the end user, as they should be aware of the size of the dataset they're inputting. Having this number in hand should make things like creating and looping through arrays a lot easier.

**Comment by sabaronett** [comment]
Hey @Nofe4108,

Hold off on further work on this. After a couple of meetings with Dan and him working on my code, we might not need this implemented in C anymore. Based on some working versions we have now (see this Jupyter notebook [example](https://github.com/sabaronett/reboundx/blob/spline/ipython_examples/MassEvolution.ipynb)), we can pass lists of values to the interpolator in Python (e.g., can use `PyMesaReader`), while maintaining all the efficiency at the C level. After we get this new interpolation code merged with his master branch, we can revisit this issue with Dan.

**Comment by sabaronett** [comment]
From Dan, https://github.com/sabaronett/reboundx/issues/22#issuecomment-606773524,
> I think the most logical way to organize it is if your example notebook just loads your txt files (taking them as given), and you create a separate repo that you can link to in your paper that shows people how to read a mesa output file and write out a text file. If we added the mesa reader into REBOUNDx and the example then for example if the mesa output format changes, then we have to update the REBOUNDx code. I think the cleanest is if we provide the minimal interface required in REBOUNDx (I.e. simple lists that you can load from text files or however you want) and leave all the rest to the user.

To be addressed in #24. Closing issue.
