### ISSUE TITLE
Test tides w/ MESA + spline

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/reboundx#15]
# Goal
Extend `tides_drag.c` to incorporate `mesa_reader.c` and `spline.c` to drive effect parameters.

## Tasks
- [ ] Determine how best to load the other two effects, e.g., from within `tides_drag_full.c` or from `problem.c`
- [ ] Update how parameters are handled w/ spline
- [ ] Compare 80 Kyr and 4 Myr tests w/ Python ver

**Comment by sabaronett** [comment]
C incorporation unnecessary; reading MESA files handled in Python w/ [py_mesa_reader](https://github.com/wmwolf/py_mesa_reader) (see [mesa2txt.ipynb](https://github.com/sabaronett/REBOUNDxPaper/blob/master/mesa2txt.ipynb) for more info); also see [ParameterInterpolation.ipynb](https://github.com/dtamayo/reboundx/blob/master/ipython_examples/ParameterInterpolation.ipynb) for an example of reading in and interpolating MESA data.

Closing issue.
