### ISSUE TITLE
interpolation.c

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/reboundx#17]
- [x] [Review](https://reboundx.readthedocs.io/en/latest/effects.html#modify-mass) and start from `modify_mass.c` ([operator](https://reboundx.readthedocs.io/en/latest/add_effect.html#operators)) w/ momentum handling 1d4f82b59be1bf3a28316cec144040b21fea33dd
- [x] Hard code array values based on `modify_mass` [Jupyter notebook](https://nbviewer.jupyter.org/github/dtamayo/reboundx/blob/master/ipython_examples/ModifyMass.ipynb) for (t, M) in `problem.c` edb5a93f609de0162a78f1bdb76656698914aeaa
- [x] [Register](https://reboundx.readthedocs.io/en/latest/add_effect.html#adding-custom-types) custom type particle param (pointer to double array) for (t, M), (t,R), (t, L), etc.; 06c87f9d3d1f60f0a7a3e383245c47c755005fec
- [x] Register array size `int n` and left-hand bracket `int klo` params 06c87f9d3d1f60f0a7a3e383245c47c755005fec
- [x] Adapt `spline.c` as a convenience function in `stellar_evo.c` 996557a5d8939e6af49fdbab66976a5aaca245c6
- [x] Implement proper func. call by ref. w/ ptr logic/arithmetic 9b0fc37d7f7343e1bbdc4ca59e358e99e7038c41
- [x] Debug seg fault b2e7a0e53867bfad6acd55d40ce8e6fababfe474
- [x] Reimplement `mass_klo` param w/o passing particle 371694ce53cddb3958035bbd1e3e7ee2c22a6cc4
- [x] Unit tests with `problem.c`  https://github.com/sabaronett/reboundx/issues/17#issuecomment-598552032
- [x] Read "[Adding Parameters With REBOUNDx](https://nbviewer.jupyter.org/github/dtamayo/reboundx/blob/master/ipython_examples/GettingStartedParameters.ipynb)" notebook
- [x] Fork Python example from [ModifyMass.ipynb](https://nbviewer.jupyter.org/github/dtamayo/reboundx/blob/master/ipython_examples/ModifyMass.ipynb) 5d7f61e25268dcf487a2731e237173cd7d88e3d4
- [x] [Manually cast](https://reboundx.readthedocs.io/en/latest/add_effect.html#adding-custom-types) custom [ctypes](https://docs.python.org/3/library/ctypes.html#arrays) in Jupyter notebook example 70583ba24c89d62e04e5275b14cede8809dc949a
- [x] Finalize `problem.c` w/o data file output a148f20d9edc61ec169a49409ffc9ca07568b2a3
- [x] Proofread all comments/documentation e1a7a7dd13a6882aa31a4f0e6aced7fb24fe4b03
- [x] Build and check documentation 2aeedc3e6c4385d179f7e702be610dbe48a9d50e
- [x] Read &sect; 2.1, "Splitting Schemes," of [paper](https://arxiv.org/pdf/1908.05634.pdf)
- [x] Check with Dan how best to implement other particle attributes, e.g., radius, luminosity, etc.
- [x] Register & implement `REBX_TYPE_POINTER` for parameter object to be adjusted #19 
- [x] Review Dan's pull request #19 (into `sabaronett:spline` from `dtamayo:spline`)
- [x] Update task list from #19 [comment](https://github.com/sabaronett/reboundx/pull/19#issue-390676670)
- [x] Make notebook example of post-MS test case, e.g., mass, radius #22 
- [x] Runtime error in malloc.c #20 
- [x] Allow for backwards integration by adjusting `klo` based on sign of `sim.dt` #21 
- [x] `problem.c` bug: Sun's mass jumps by 0.2 at t=2.5e3. (resolved in #23?)
- [x] Revise documentation (add Noah as co-author on tides) ae060e6b6997e9fa9749ba146dadd03e93ad09d5
- [x] Create pull request (into `dtamayo:master` from `sabaronett:spline`) https://github.com/dtamayo/reboundx/pull/47

**Comment by sabaronett** [comment]
@dtamayo,

I've implemented a first draft of `stellar_evo.c`, etc., in https://github.com/sabaronett/reboundx/commit/996557a5d8939e6af49fdbab66976a5aaca245c6, but it almost immediately runs into a seg fault (likely first operator call as the initial heartbeat is able to write out). As I suspected it might have something to do with how I'm passing and later dereferencing the time-mass arrays as `REBX_TYPE_POINTER`s, I made some changes in 1f7488945baf8476aa405a9e4187e8eafe530e67 (latest commit), but this now yields the following compile time errors:
```bash
stellar_evo.c: In function ‘rebx_stellar_evo’:
stellar_evo.c:140:30: error: invalid initializer
                 double x[] = *xptr; // COMPILE ERROR
                              ^
stellar_evo.c:141:30: error: invalid initializer
                 double y[] = *yptr; // COMPILE ERROR
                              ^
stellar_evo.c:147:31: error: invalid initializer
                 double y2[] = *y2ptr;
                               ^
```

I'll keep debugging this week, but thought I should share in case you are already aware of the pitfalls or a solution, or have any other suggestions about the code.

Thanks.

**Comment by sabaronett** [comment]
@dtamayo,

I brushed up on the following C topics:
- function call by [value](https://beginnersbook.com/2014/01/c-function-call-by-value-example/) vs. [reference](https://beginnersbook.com/2014/01/c-function-call-by-reference-example/)
- [pointers to arrays](https://beginnersbook.com/2014/01/c-pointer-to-array-example/) w/ pointer arithmetic
- [passing arrays to functions](https://beginnersbook.com/2014/01/c-passing-array-to-function-example/)

I then implemented the pointer-arithmetic scheme by rewriting my original, standalone `spline.c` file (as `spline_ptrs.c`) and verified it works properly, producing the same results as before (see [here](https://github.com/sabaronett/demo-lab/commit/d95950f8bb0f48315d384346af9ca724ca8ef522)). Afterwards, I implemented the same in `stellar_evo.c`, and updated `problem.c` and `core.c` accordingly in 9b0fc37d7f7343e1bbdc4ca59e358e99e7038c41. 

I'm no longer getting any compile-time errors, but I'm still getting a seg fault during the first operator call. I'll try stepping through with a debugger in VS Code tomorrow when I have some time and see if I can figure out where the issue is.

**Comment by sabaronett** [comment]
@dtamayo,

I got it working finally (b2e7a0e53867bfad6acd55d40ce8e6fababfe474), and confirmed stellar mass loss and orbital expansion. The seg fault was caused when trying to get/set the registered `mass_klo` param in the `splint()` function while passing the `particle` struct. When I get time tomorrow (Thurs), I'll reimplement the param without passing the particle to the function, graph the output data, and make a Jupyter notebook.

**Comment by sabaronett** [comment]
Graphical results from `problem.c` star/planet data outputs.
![mass_loss](https://user-images.githubusercontent.com/51060809/76591576-076ea400-64ae-11ea-9d14-14b37ce712d7.png)
![orbital_expansion](https://user-images.githubusercontent.com/51060809/76591581-0c335800-64ae-11ea-8f13-c4080476c42c.png)

**Comment by dtamayo** [comment]
This is great! I'm home with kids today after their school closed, but will
take a look asap. Great work!

**Comment by sabaronett** [comment]
@dtamayo, I finished the first draft of the Jupyter notebook in https://github.com/sabaronett/reboundx/commit/70583ba24c89d62e04e5275b14cede8809dc949a. Should I set the integrator to IAS15 w/ a fixed timestep to get rid of the warning in cell 5's output?

**Comment by sabaronett** [comment]
Hey Dan, this checklist is pretty much done! As for documentation, I updated the main header in `interpolation.c` to match that of other non-effects/operators (e.g., integrate_force and integrator_rk2) in 6c8b70217e2b290abcfe4a5339268de61e6c74e7. Let me know if there's something else I need to do on the docs front.

If #21 and #24 can be closed, I'll submit a pull request to merge into your master.
