### ISSUE TITLE
tides_drag.c

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/reboundx#6]
## Tasks
- [x] Develop from `migration_force` [effect/example](https://rebound.readthedocs.io/en/latest/ipython/Forces.html)
- [x] Go thru tides/rad. existing fxns/logic
- [x] Create equivalent `tides_drag` fxns
- [x] Test `tides_drag` effect (use https://github.com/sabaronett/reboundx/issues/4) fc3abd90b1926b29118451fc1a644dda7a32efd4
- [x] Use `omega = po.n`
- [x] Output and plot [COM](https://rebound.readthedocs.io/en/latest/c_api_toolsrebfunctions.html#_CPPv411reb_get_comP14reb_simulation) position
- [x] Add an equal and opposite force to the primary when you update the accelerations to keep the center of mass fixed (see the other forces for an example) a99e2fe122b54d3a12df3a72ea74e3f7b81b8a43
- [x] Test the COM hasn't moved between integrations for large particle masses https://github.com/sabaronett/reboundx/issues/6#issuecomment-583256126
- [x] Register and test [add'l parameters](https://reboundx.readthedocs.io/en/latest/add_effect.html#adding-parameters) (e.g., `R0`, `L0`, `Omega`, `lambda2`) 190cf8c5852bbd78432b0fe4f8da76667ca1df52
- [x] Incorporate and test dynamic "primary" param/logic c0bd209e81708e26d88b64d3de6019107b6ce89b
- [x] Fix/make new virtual env for rebx
- [x] Create and test 70 Kyr Python example b365ad7a4d4d6f5d66ecce1b975909b41aa328c2
- [x] Finish [documentation](https://reboundx.readthedocs.io/en/latest/add_effect.html#add-your-effect-to-the-main-documentation-page) 2f8b6c070521bbe6543adcae14e8052ed1b60a79
   - [x] Finalize comments 
   - [x] Finalize description (including formula assumptions)
   - [x] Finalize effect/particle parameters
   - [x] Check HTML https://github.com/sabaronett/reboundx/issues/6#issuecomment-584322072
- [x] Cleanup
   - [x] Turn OpenGL back on in Makefile 9c330301218094327d61d4e5acb69b6d76e1d224
   - [x] Backup and remove `stark_effect` (example, `effect.c`, `core.c`, `core.h`) 8e5f2569c033fae3b0d38910bac112af81c81416
   - [x] Backup and remove `migration_force` and parameter (example, `effect.c`, `core.c`, `core.h`) 8e5f2569c033fae3b0d38910bac112af81c81416
   - [x] Backup and remove misc. examples, e.g., `ss`, `sun_earth` 8e5f2569c033fae3b0d38910bac112af81c81416
   - [x] Backup and remove data output in `problem.c` 9c330301218094327d61d4e5acb69b6d76e1d224
   - [x] Root dir. (misc. files)
   - [x] .rst files (docs)? e048432f4aef176019c06215ba59df8980dd9f65
   - [x] setup.py (products of `make`) da5ac2c5a59d1f28fcff50f34a4581fd50485784
- [x] [Final checklist](https://reboundx.readthedocs.io/en/latest/add_effect.html#contributing-your-effect-to-reboundx)
- [x] Submit pull request https://github.com/dtamayo/reboundx/pull/44
- [x] Add a convenience function to calculate the relevant tidal parameters from the constants we're using from Zahn.

## Add'l Tests
- https://github.com/sabaronett/reboundx/commit/fc3abd90b1926b29118451fc1a644dda7a32efd4#commitcomment-37111540
- [x] Check and run numerical tests for _analytic solutions_ to formula (derived time evolution w/ approximations) https://github.com/dtamayo/reboundx/pull/44#issuecomment-585436171
- https://github.com/sabaronett/reboundx/issues/6#issuecomment-583392701
- [x] Don't move to COM before start, and add +10 to `.vy` of both particles. Check all plots. https://github.com/sabaronett/reboundx/issues/6#issuecomment-584349982
- [x] Test `q/1-q` factors w/ large mass ratio cases

**Comment by sabaronett** [comment]
Results of fc3abd90b1926b29118451fc1a644dda7a32efd4:
![tides_drag_result](https://user-images.githubusercontent.com/51060809/73598575-ffa30380-44ee-11ea-84bc-933d8be5a868.png)

**Comment by sabaronett** [comment]
@dtamayo,
Since the heart of this tidal drag effect (as described in Eq. 4 of [Schroder & Smith](https://arxiv.org/abs/0801.4031)) is technically achieved with fc3abd9, should I go ahead and finish it as its own separate implementation (similar to `gr` and `gr_full`) and send our first pull request? All that's left to do for that first implementation is register a couple params, make a Python example, and finalize the documentation. I can foresee this "lite" version being useful for people who'd like to employ the effect _without_ MESA or external stellar data.

**Comment by sabaronett** [comment]
@dtamayo, thanks for the suggestions in https://github.com/sabaronett/reboundx/commit/fc3abd90b1926b29118451fc1a644dda7a32efd4#commitcomment-37111540_. I really appreciate the guidance.

Following the examples of `tides_precession.c` and `central_force.c`, I added a reverse torque to the primary in a99e2fe122b54d3a12df3a72ea74e3f7b81b8a43.
https://github.com/sabaronett/reboundx/blob/a99e2fe122b54d3a12df3a72ea74e3f7b81b8a43/src/tides_drag.c#L105-L108

I also "tested" that the COM doesn't move using the `reb_get_com(sim)` tool in cb1fec1e007d5335f19732432f283f9c3c9dc08e, but wanted to check with you that the methodology is valid. In particular, these are the results before and after the addition of the reverse torque in the same 80 Kyr test in `problem.c`:
### Before (without reverse torque)
![COM_tides_drag_before](https://user-images.githubusercontent.com/51060809/73913895-ff976080-486c-11ea-8644-579d525c4c98.png)
### After (with reverse torque)
![COM_tides_drag_after](https://user-images.githubusercontent.com/51060809/73913943-1342c700-486d-11ea-8a48-e209184acb47.png)
Expecting to see a constant zero over time for the "after," I tried running for comparison the same test for a simple Sun-Earth simulation with _no_ REBOUNDx add'l forces in d4b47a379ded776b4dce9a19621813b4523388f3 and found the following:
### Simple Sun-Earth (no add'l forces)
![COM_sun_earth](https://user-images.githubusercontent.com/51060809/73914285-d75c3180-486d-11ea-91b6-b36f46c90050.png)

I'm guessing since these fluctuations are on the order of e-21 to e-22, this is a result of error propagation due to float operations?

Also, does the fact that the COM doesn't appear to significantly move even before I applied the reverse torque have anything to do with the force being velocity dependent (i.e., drag-like), unlike the examples in `tides_precession.c` and `central_force.c` (position-based)?

**Comment by dtamayo** [comment]
Try pumping up the mass of the planet to large values. Not putting in the back-reaction should then become obvious. I don't think velocity vs position dependent matters--if you add additional accelerations to some of the particles the COM will drift. 

In reality, these back-reaction accelerations would go into changing the rotation of the star, but since that's not being modeled, it's probably better to put it into the star's bulk motion so nothing potentially drifts.

**Comment by sabaronett** [comment]
# COM Tests
- WHFast integrator
- 11th order symplectic corrector
## _m_<sub>⊕</sub>/_M_<sub>☉</sub> = 0.5
### No back-reaction
![q_half_without](https://user-images.githubusercontent.com/51060809/73959878-dacbd900-48be-11ea-9591-e82d65bdc90a.png)
### With back-reaction
![q_half_with](https://user-images.githubusercontent.com/51060809/73959905-e28b7d80-48be-11ea-8631-e68504ac3635.png)
## _m_<sub>⊕</sub>/_M_<sub>☉</sub> = 1.0
### No back-reaction
![M_parity_without](https://user-images.githubusercontent.com/51060809/73959921-e919f500-48be-11ea-92af-6b1ca5bb9ee7.png)
### With back-reaction
![M_parity_with](https://user-images.githubusercontent.com/51060809/73959934-ef0fd600-48be-11ea-9a9a-797802cd3c26.png)

**Comment by dtamayo** [comment]
Nice. It should be better than this though, at least with IAS15. Are you using IAS15 and setting r->force_is_velocity_dependent = 1? Using this with WHFast should also be fine (see our REBOUNDx paper), but won't be exact. But you should get it to at least 10^-16 with IAS15, so that's a useful test that things are implemented correctly.

Thinking about it more, the equations are assuming a circular orbit, damping the semimajor axis of the two-body planet-Sun orbit, I.e., damping v1-v0. So just like you use p0.v for |v1-v0| in vmag, you should be using that in the accelerations for each of the components (v1x-v0x) etc. Then I think the condition that (a1-a0) is proportional to (v1-v0), while still maintaining the COM (m1a1 + m0a0) = 0 is that

a1 = prefac/(1-q) * (v1-v0)
a0 = -prefac*q/(1-q) * (v1-v0)

(If you plug those in above they should match). I think the net effect should be that if you initialize your planet on a circular orbit (using particles[0] as the primary), using the above equations will keep the eccentricity 0 to machine precision as it evolves inward. With the current equations the eccentricity should be of order the mass ratio I would guess. 

I *don't* think this matters for most cases (and if you use WHFast then things aren't exactly correct anyway for velocity-dependent forces), but checking these limits with IAS15 gives you confidence that they are correct, and means that you won't get as many spurious cases if people try it with very massive planets, or if the tides get really strong etc.

**Comment by sabaronett** [comment]
You suspected right: I _was_ using WHFast in the previous https://github.com/sabaronett/reboundx/issues/6#issuecomment-583004630. Below are _m_<sub>⊕</sub>/_M_<sub>☉</sub> = 0.5 tests but with IAS15 and `force_is_velocity_dependent = 1` (_before_ making any changes to `tides_drag.c`):
### w/o back-reaction (IAS15)
![pre-without](https://user-images.githubusercontent.com/51060809/74000995-d7683a00-491e-11ea-8ce2-fc4638a52db0.png)
### w/ back-reaction (IAS15)
![pre-with](https://user-images.githubusercontent.com/51060809/74000998-da632a80-491e-11ea-90f6-3a4b8d0ff2b6.png)
On the order of machine precision as you predicted.
## Eccentricity Correction
I made the changes you suggested in 795e5c62db7ca49c44cdd9fa6d339e1cf9b3c3dc:
https://github.com/sabaronett/reboundx/blob/795e5c62db7ca49c44cdd9fa6d339e1cf9b3c3dc/src/tides_drag.c#L112-L117
But it doesn't seem to have done much compared to before the correction, and neither are zero to within machine precision.
![comp](https://user-images.githubusercontent.com/51060809/74006586-f53e9a80-4930-11ea-9c52-88434b2a0310.png)

**Comment by dtamayo** [comment]
OK, yeah that does make sense in retrospect! With the tides the force is no longer exactly Keplerian, so the eccentricity should be of order the ratio of the tidal forces to the original gravitational forces from the Sun.

I still think this is the right implementation. I think you'll notice very different answers between original and new in the case where you don't move to com at the beginning (say if you initialize them how you are and add +10 to both particles' vy. That doesn't change (v1-v0), but makes a big difference to the original implementation that only used v1. the q/1-q factors are probably only visible for very large mass ratio cases.

Thanks for implementing all these improvements!

**Comment by sabaronett** [comment]
Of course! And thanks again for your input&mdash;I would never have thought to test these on my own. I'm going to try to finish out the rest of the task list, so I can submit a pull request sooner than later. But I've added those two cases to an "Add'l Tests" list to experiment with afterwards.

**Comment by sabaronett** [comment]
@dtamayo, I registered the add'l params in 190cf8c5852bbd78432b0fe4f8da76667ca1df52, but I wasn't sure whether to use `particle.r` (current ver.) or `...particles[0].ap, "R_tides"...` for the primary physical radius. The effect/formula only requires it for the primary. Which do you recommend?

**Comment by dtamayo** [comment]
I think it makes sense to use a separate parameter so that the user can for
example artificially tune of the tides' effect,  but keep the physical
radius of the star constant to check for close encounters

**Comment by sabaronett** [comment]
From [6.3.1. Add Your Effect to the Main Documentation Page!](https://reboundx.readthedocs.io/en/latest/add_effect.html#add-your-effect-to-the-main-documentation-page)
> You can check how everything looks by navigating to reboundx/doc and typing make clean, then make html. Then navigate to reboundx/doc/_build/html and open index.html in your browser. The main effects page (with the tables) is on the left: REBx Effects & Parameters. The automatically included documentation will be under API Documentation (Python) and API Documentation (C).

After installing both `sphinx` and `breathe`, encountered the following, attempting to execute `make html`:
```bash
Exception occurred:
  File "/home/stanley/miniconda3/envs/rebx/lib/python3.7/site-packages/breathe/directives.py", line 697, in get_mtime
    raise MTimerError('Cannot find file: %s' % os.path.realpath(filename))
breathe.directives.MTimerError: Cannot find file: /home/stanley/GitHub/sabaronett/reboundx/doc/doxygen/xml/index.xml
```

**Comment by sabaronett** [comment]
> I think you'll notice very different answers between original and new in the case where you don't move to com at the beginning (say if you initialize them how you are and add +10 to both particles' vy. That doesn't change (v1-v0), but makes a big difference to the original implementation that only used v1.

@dtamayo, I tried the following in `problem.c` _without_ `reb_move_to_com(sim);`
```c
struct reb_particle sun = {0}; // initialize w/ zeroes
sun.m = 0.86;                  // in Msun
sun.vy += 10.;
reb_add(sim, sun);

struct reb_orbit eo = {0};     // for Earth
// double e_mass = 0.43;       // limiting case tests
double e_mass = 2.988e-6;
eo.a = 1.0;                    // in AU
struct reb_particle ep = reb_tools_orbit_to_particle(sim->G, sun, e_mass, eo.a, eo.e, eo.inc, eo.Omega, eo.omega, eo.f);
ep.vy += 10.;
reb_add(sim, ep);
```
And here are the results I got with the old version and new implementation (i.e., 795e5c62db7ca49c44cdd9fa6d339e1cf9b3c3dc):
### Old
![old](https://user-images.githubusercontent.com/51060809/74113063-9ce8e200-4b56-11ea-8b1f-a363f11d0eec.png)

### New
![new](https://user-images.githubusercontent.com/51060809/74113028-572c1980-4b56-11ea-88d1-bc4259315e88.png)

Not much difference, but, more importantly, the results seem way off from earlier. It seems to only occur when I add the +10 to `.vy`. If I comment that line out, here's what I get (same as before), _with or without_ `reb_move_to_com(sim);`
### Normal
![normal](https://user-images.githubusercontent.com/51060809/74113174-66f82d80-4b57-11ea-877b-4bc8cf6eca49.png)
Thoughts?

**Comment by dtamayo** [comment]
It may be that you need to add 10 to vy to both particles after you initialize both. I think you're asking it for planet pos/vel relative to a star with vy += 10, and then you're adding 10 to the planet after that, which makes it unbound. Try moving the star +=10 to the end

**Comment by dtamayo** [comment]
Thanks for all the work you're putting into this. This is also helping improve the documentation so it's easier for other people to add effects!

You're right about the documentation problem. You also need to install doxygen to generate the C documentation. I've updated the add effect section in the doc on the master branch. Could you check whether that works for you? Also please feel free to open an issue or update the add a new effect page wherever you feel like more detail would be useful!

**Comment by sabaronett** [comment]
Worked perfectly!
![image](https://user-images.githubusercontent.com/51060809/74185007-a62c8a00-4bfc-11ea-80ea-15abe008cb1e.png)
Thanks!

**Comment by sabaronett** [comment]
> Try moving the star +=10 to the end

Believe it or not, after trying several different combinations&mdash;starting with your suggestion&mdash;it was `ep.vy += 10.;` that I needed to move to the end! I think it makes sense because adding 10 to `vy` _after_ using `reb_tools_orbit_to_particle()`, but _before_ adding it to the sim, is what creates that "unbound" condition you alluded to. Either way, thanks for the tip!

Here are the results!
### With your difference in velocity correction:
![new](https://user-images.githubusercontent.com/51060809/74189058-99ac2f80-4c04-11ea-93c4-df5d3000aab8.png)
No change, as you predicted.
### Original formulation, without the correction:
![old](https://user-images.githubusercontent.com/51060809/74189088-a466c480-4c04-11ea-8d4a-8605cc66dd50.png)
Big difference, sure enough!

**Comment by dtamayo** [comment]
Great, good detective work!

**Comment by sabaronett** [comment]
Thanks!

> the q/1-q factors are probably only visible for very large mass ratio cases.

Here are some results for a mass ratio of _q_ = 0.5, with almost a half-million times smaller &lambda;<sub>2</sub> than before to get approximately the same 70 Kyr engulf time:
### New, _q_/(1-_q_) = 1
![new](https://user-images.githubusercontent.com/51060809/74194170-9c5f5280-4c0d-11ea-8bfc-341e480dffdf.png)
### Old, just _q_ = 0.5
![old](https://user-images.githubusercontent.com/51060809/74194258-c9136a00-4c0d-11ea-884d-6238399c0057.png)

**Comment by dtamayo** [comment]
Which do you think is right solution? Do you have an analytic solution to compare to? It must be in several papers or Murray and Dermott. Or it should be solvable by dE/dt = F dot v, E = -Gm0m1/a, relating dE/dt to da/dt and integrating by separation of variables.

I should have time tomorrow to go through the pull request.  Thanks again!

**Comment by sabaronett** [comment]
I'm not sure just yet, but I have some leads on an analytic solution. The formulation was originally analyzed and applied to binary star orbits. I have to work on some other assignments due this week, but then I'll start looking at the related papers and keep Murray and Dermott and your suggestions as backups.

Thanks again for your help!

**Comment by sabaronett** [comment]
Commits and updates merged in https://github.com/dtamayo/reboundx/pull/45.

Closing issue.
